# Introduction to Sprint - Machine Learning Scratch

### [Problem 1] Scratch of train_test_split

In [1]:
import numpy as np
import pandas as pd
from math import ceil

In [2]:
def scratch_train_test_split(X, y, train_size=0.8):
    """Split the validation data.
    Parameters
    ----------
    X : ndarray
      Training data (n_samples, n_features)
    y : ndarray
      Correct value (n_samples,)
    train_size : float
      Specify what percentage to use as train (0 < train_size < 1)
    Returns
    -------
    X_train : ndarray
      Training data (n_samples, n_features)
    X_test : ndarray
      Validation data (n_samples, n_features)
    y_train : ndarray
      Correct value of training data (n_samples,)
    y_test : ndarray
      Correct value of verification data (n_samples,)
    """
    # TODO
    if isinstance(y, range) or isinstance(y, list):
        y = np.array(y)
    assert X.shape[0] > 0 and y.shape[0] > 0, 'At least one row required in X and y'
    assert X.shape[0] == y.shape[0], '2 array must have same n_samples'
    assert train_size > 0 and train_size < 1, 'train_size must be in [0, 1]'
    
    n_samples = X.shape[0]
    n_train = ceil(n_samples * train_size)
    
    train_idx = np.random.choice(X.shape[0], size=n_train, replace=False)
    test_idx = [i for i in range(n_samples) if i not in train_idx]
    
    X_train = X[train_idx, :]
    y_train = y[train_idx]
    X_test = X[test_idx, :]
    y_test = y[test_idx]
    return X_train, X_test, y_train, y_test

In [3]:
X, y = np.arange(20).reshape((10, 2)), np.arange(10)
print(X)
print(y)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, train_size=0.6)
print('X_train\n', X_train)
print('y_train\n', y_train)
print('X_test\n', X_test)
print('y_test\n', y_test)

X_train
 [[12 13]
 [ 6  7]
 [ 4  5]
 [10 11]
 [18 19]
 [14 15]]
y_train
 [6 3 2 5 9 7]
X_test
 [[ 0  1]
 [ 2  3]
 [ 8  9]
 [16 17]]
y_test
 [0 1 4 8]


In [5]:
print(X.shape, y.shape)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(10, 2) (10,)
(6, 2) (6,) (4, 2) (4,)


In [6]:
# Simple data set 1 creation code
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0,0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, n_samples // 2)
f1 = np.random.multivariate_normal(f1, cov, n_samples // 2)
X1 = np.concatenate([f0, f1])
y1 = np.concatenate([
    np.full(n_samples // 2, 1),
    np.full(n_samples // 2, -1)
])

In [7]:
X1_train, X1_test, y1_train, y1_test = scratch_train_test_split(X1, y1)
print(X1.shape, y1.shape)
print(X1_train.shape, y1_train.shape, X1_test.shape, y1_test.shape)

(500, 2) (500,)
(400, 2) (400,) (100, 2) (100,)


In [8]:
# Simple data set 2 creation code
X2 = np.array([[-0.44699 , -2.8073  ],[-1.4621  , -2.4586  ],
       [ 0.10645 ,  1.9242  ],[-3.5944  , -4.0112  ],
       [-0.9888  ,  4.5718  ],[-3.1625  , -3.9606  ],
       [ 0.56421 ,  0.72888 ],[-0.60216 ,  8.4636  ],
       [-0.61251 , -0.75345 ],[-0.73535 , -2.2718  ],
       [-0.80647 , -2.2135  ],[ 0.86291 ,  2.3946  ],
       [-3.1108  ,  0.15394 ],[-2.9362  ,  2.5462  ],
       [-0.57242 , -2.9915  ],[ 1.4771  ,  3.4896  ],
       [ 0.58619 ,  0.37158 ],[ 0.6017  ,  4.3439  ],
       [-2.1086  ,  8.3428  ],[-4.1013  , -4.353   ],
       [-1.9948  , -1.3927  ],[ 0.35084 , -0.031994],
       [ 0.96765 ,  7.8929  ],[-1.281   , 15.6824  ],
       [ 0.96765 , 10.083   ],[ 1.3763  ,  1.3347  ],
       [-2.234   , -2.5323  ],[-2.9452  , -1.8219  ],
       [ 0.14654 , -0.28733 ],[ 0.5461  ,  5.8245  ],
       [-0.65259 ,  9.3444  ],[ 0.59912 ,  5.3524  ],
       [ 0.50214 , -0.31818 ],[-3.0603  , -3.6461  ],
       [-6.6797  ,  0.67661 ],[-2.353   , -0.72261 ],
       [ 1.1319  ,  2.4023  ],[-0.12243 ,  9.0162  ],
       [-2.5677  , 13.1779  ],[ 0.057313,  5.4681  ]])
y2 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
X2_train, X2_test, y2_train, y2_test = scratch_train_test_split(X2, y2)
print(X2.shape, y2.shape)
print(X2_train.shape, y2_train.shape, X2_test.shape, y2_test.shape)

(40, 2) (40,)
(32, 2) (32,) (8, 2) (8,)


### [Problem 2] Creating a code to solve the classification problem

In [10]:
from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.datasets import load_iris

In [11]:
# Classification on iris dataset
X = pd.DataFrame(data=load_iris().data, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
y = pd.DataFrame(load_iris().target, columns=[('Species')])
df = pd.concat([X, y], axis=1)
df = df[df.Species != 0]
X = df.drop(columns=['Species']).values
y = df['Species'].values

In [12]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, train_size=0.8)

In [13]:
from sklearn.preprocessing import StandardScaler

def scale(X_train, X_test):
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train_scaled = scaler.transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    return X_train_scaled, X_test_scaled

In [14]:
X_train_scaled, X_test_scaled = scale(X_train, X_test)

In [15]:
sgd = SGDClassifier(loss='log')
sgd.fit(X_train_scaled, y_train)
sgd.score(X_test_scaled, y_test)

0.9

In [16]:
sgd_predict = sgd.predict(X_test_scaled)
result_sgd = pd.DataFrame([sgd_predict, y_test], index=['Predict', 'Actual value'])
result_sgd

0   1   2   3   4   5   6   7   ...  12  13  14  15  16  17  18  19
Predict        1   2   1   1   1   2   1   1  ...   2   2   2   2   2   2   2   2
Actual value   1   1   1   1   1   1   1   1  ...   2   2   2   2   2   2   2   2

[2 rows x 20 columns]

In [17]:
svc = SVC()
svc.fit(X_train_scaled, y_train)
svc.score(X_test_scaled, y_test)

0.9

In [18]:
svc_predict = svc.predict(X_test_scaled)
result_svc = pd.DataFrame([svc_predict, y_test], index=['Predict', 'Actual value'])
result_svc

0   1   2   3   4   5   6   7   ...  12  13  14  15  16  17  18  19
Predict        1   2   1   1   1   2   1   1  ...   2   2   2   2   2   2   2   2
Actual value   1   1   1   1   1   1   1   1  ...   2   2   2   2   2   2   2   2

[2 rows x 20 columns]

In [19]:
dtc = DecisionTreeClassifier()
dtc.fit(X_train_scaled, y_train)
dtc.score(X_test_scaled, y_test)

0.85

In [20]:
dtc_predict = dtc.predict(X_test_scaled)
result_dtc = pd.DataFrame([dtc_predict, y_test], index=['Predict', 'Actual value'])
result_dtc

0   1   2   3   4   5   6   7   ...  12  13  14  15  16  17  18  19
Predict        1   2   1   1   1   2   1   1  ...   2   2   2   2   2   2   1   2
Actual value   1   1   1   1   1   1   1   1  ...   2   2   2   2   2   2   2   2

[2 rows x 20 columns]

In [21]:
# Classification on simple data set 1 
# (scratch_train_test_split on the dataset has already been done
# in problem 1)
X1_train_scaled, X1_test_scaled = scale(X1_train, X1_test)

In [22]:
sgd = SGDClassifier(loss='log')
sgd.fit(X1_train_scaled, y1_train)
sgd.score(X1_test_scaled, y1_test)

1.0

In [23]:
pd.set_option('display.max_columns', None)
sgd_predict = sgd.predict(X1_test_scaled)
result_sgd = pd.DataFrame([sgd_predict, y1_test], index=['Predict', 'Actual value'])
result_sgd

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  \
Predict        1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
Actual value   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   

              16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  \
Predict        1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
Actual value   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   

              32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  \
Predict        1   1   1   1   1   1   1   1   1  -1  -1  -1  -1  -1  -1  -1   
Actual value   1   1   1   1   1   1   1   1   1  -1  -1  -1  -1  -1  -1  -1   

              48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  \
Predict       -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   
Actual value  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   

              64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  \
Predict       -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   
Actual value  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   

              80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  \
Predict       -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   
Actual value  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   

              96  97  98  99  
Predict       -1  -1  -1  -1  
Actual value  -1  -1  -1  -1

In [24]:
svc = SVC()
svc.fit(X1_train_scaled, y1_train)
svc.score(X1_test_scaled, y1_test)

1.0

In [25]:
svc_predict = svc.predict(X1_test_scaled)
result_svc = pd.DataFrame([svc_predict, y1_test], index=['Predict', 'Actual value'])
result_svc

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  \
Predict        1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
Actual value   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   

              16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  \
Predict        1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
Actual value   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   

              32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  \
Predict        1   1   1   1   1   1   1   1   1  -1  -1  -1  -1  -1  -1  -1   
Actual value   1   1   1   1   1   1   1   1   1  -1  -1  -1  -1  -1  -1  -1   

              48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  \
Predict       -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   
Actual value  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   

              64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  \
Predict       -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   
Actual value  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   

              80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  \
Predict       -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   
Actual value  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   

              96  97  98  99  
Predict       -1  -1  -1  -1  
Actual value  -1  -1  -1  -1

In [26]:
dtc = DecisionTreeClassifier()
dtc.fit(X1_train_scaled, y1_train)
dtc.score(X1_test_scaled, y1_test)

1.0

In [27]:
dtc_predict = dtc.predict(X1_test_scaled)
result_dtc = pd.DataFrame([dtc_predict, y1_test], index=['Predict', 'Actual value'])
result_dtc

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  \
Predict        1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
Actual value   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   

              16  17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  \
Predict        1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   
Actual value   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   1   

              32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47  \
Predict        1   1   1   1   1   1   1   1   1  -1  -1  -1  -1  -1  -1  -1   
Actual value   1   1   1   1   1   1   1   1   1  -1  -1  -1  -1  -1  -1  -1   

              48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  \
Predict       -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   
Actual value  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   

              64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  \
Predict       -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   
Actual value  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   

              80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  \
Predict       -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   
Actual value  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   

              96  97  98  99  
Predict       -1  -1  -1  -1  
Actual value  -1  -1  -1  -1

In [28]:
# Classification on simple data set 2
# (scratch_train_test_split on the dataset has already been done
# in problem 1)
X2_train_scaled, X2_test_scaled = scale(X2_train, X2_test)

In [29]:
sgd = SGDClassifier(loss='log')
sgd.fit(X2_train_scaled, y2_train)
sgd.score(X2_test_scaled, y2_test)

0.75

In [30]:
sgd_predict = sgd.predict(X2_test_scaled)
result_sgd = pd.DataFrame([sgd_predict, y2_test], index=['Predict', 'Actual value'])
result_sgd

0  1  2  3  4  5  6  7
Predict       1  0  1  0  1  1  1  1
Actual value  0  0  0  0  1  1  1  1

In [31]:
svc = SVC()
svc.fit(X2_train_scaled, y2_train)
svc.score(X2_test_scaled, y2_test)

0.625

In [32]:
svc_predict = svc.predict(X2_test_scaled)
result_svc = pd.DataFrame([svc_predict, y2_test], index=['Predict', 'Actual value'])
result_svc

0  1  2  3  4  5  6  7
Predict       0  1  0  1  0  1  1  1
Actual value  0  0  0  0  1  1  1  1

In [33]:
dtc = DecisionTreeClassifier()
dtc.fit(X2_train_scaled, y2_train)
dtc.score(X2_test_scaled, y2_test)

0.375

In [34]:
dtc_predict = dtc.predict(X2_test_scaled)
result_dtc = pd.DataFrame([dtc_predict, y2_test], index=['Predict', 'Actual value'])
result_dtc

0  1  2  3  4  5  6  7
Predict       0  1  1  1  1  0  0  1
Actual value  0  0  0  0  1  1  1  1

In [36]:
df_house = pd.read_csv('sample_data/train.csv')
df_house.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1         Lvl    AllPub       FR2       Gtl      Veenker      Feedr   
2         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
3         Lvl    AllPub    Corner       Gtl      Crawfor       Norm   
4         Lvl    AllPub       FR2       Gtl      NoRidge       Norm   

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     2Story            7            5       2003   
1       Norm     1Fam     1Story            6            8       1976   
2       Norm     1Fam     2Story            7            5       2001   
3       Norm     1Fam     2Story            7            5       1915   
4       Norm     1Fam     2Story            8            5       2000   

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
1          1976     Gable  CompShg     MetalSd     MetalSd       None   
2          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace   
3          1970     Gable  CompShg     Wd Sdng     Wd Shng       None   
4          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace   

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0       196.0        Gd        TA      PConc       Gd       TA           No   
1         0.0        TA        TA     CBlock       Gd       TA           Gd   
2       162.0        Gd        TA      PConc       Gd       TA           Mn   
3         0.0        TA        TA     BrkTil       TA       Gd           No   
4       350.0        Gd        TA      PConc       Gd       TA           Av   

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          GLQ         706          Unf           0        150          856   
1          ALQ         978          Unf           0        284         1262   
2          GLQ         486          Unf           0        434          920   
3          ALQ         216          Unf           0        540          756   
4          GLQ         655          Unf           0        490         1145   

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        Ex          Y      SBrkr       856       854             0   
1    GasA        Ex          Y      SBrkr      1262         0             0   
2    GasA        Ex          Y      SBrkr       920       866             0   
3    GasA        Gd          Y      SBrkr       961       756             0   
4    GasA        Ex          Y      SBrkr      1145      1053             0   

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710             1             0         2         1             3   
1       1262             0             1         2         0             3   
2       1786             1             0         2         1             3   
3       1717             1             0         1         0             3   
4       2198             1             0         2         1             4   

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          Gd             8        Typ           0         NaN   
1             1          TA             6        Typ           1          TA   
2             1          Gd             6        Typ           1          TA   
3             1          Gd            

In [37]:
X_house = df_house[['GrLivArea', 'YearBuilt']].values
y_house = df_house['SalePrice'].values

In [40]:
X_house_train, X_house_test, y_house_train, y_house_test = scratch_train_test_split(X_house, y_house, train_size=0.8)
X_house_train_scaled, X_house_test_scaled = scale(X_house_train, X_house_test)

In [41]:
from sklearn.linear_model import SGDRegressor
pd.set_option("precision", 1)
sgd_house = SGDRegressor()
sgd_house.fit(X_house_train_scaled, y_house_train)
# Get coefficient of determination R^2
sgd_house.score(X_house_test_scaled, y_house_test)

0.7306468999915083

In [ ]:
sgd_house_predict = sgd_house.predict(X_house_test_scaled)
result_sgdh = pd.DataFrame([sgd_house_predict, y_house_test], index=['Predict', 'Actual value'])
result_sgdh

### [Problem 3] Creating a code to solve the regression problem

In [42]:
from sklearn.linear_model import LinearRegression

X_house_train, X_house_test, y_house_train, y_house_test = scratch_train_test_split(X_house, y_house, train_size=0.8)
lr = LinearRegression()
lr.fit(X_house_train_scaled, y_house_train)
lr.score(X_house_test_scaled, y_house_test)

0.006857539232573484

In [43]:
lr_predict = lr.predict(X_house_test_scaled)
result_lr = pd.DataFrame([lr_predict, y_house_test], index=['Predict', 'Actual value'])
result_lr

0         1         2         3         4         5    \
Predict       188367.8  180912.7  174528.8  184728.9  175266.0  173128.0   
Actual value  181500.0  223500.0  140000.0  118000.0  129500.0  345000.0   

                   6         7         8         9         10        11   \
Predict       177606.5  178194.7  178582.8  183782.1  199386.8  176626.7   
Actual value  154000.0  179900.0  249700.0  172500.0  101000.0  202500.0   

                   12        13        14        15        16        17   \
Predict       179334.0  187751.7  190795.3  190061.1  172552.9  175508.2   
Actual value  180000.0  226000.0  244000.0  129500.0  164500.0   85000.0   

                   18        19        20        21        22        23   \
Predict       175265.1  180952.9  177298.2  202848.9  174321.1  175448.0   
Actual value  123600.0  185000.0   94750.0  118964.0  190000.0  180000.0   

                   24        25        26        27        28        29   \
Predict       178892.4  174906.4  195847.9  189409.0  186142.8  181283.2   
Actual value  139000.0  155000.0  320000.0   84500.0  155000.0  109500.0   

                   30        31        32        33        34        35   \
Predict       177436.1  180584.5  201157.8  178000.9  183307.0  175710.7   
Actual value  269500.0  127500.0  325624.0  183500.0  184000.0  243000.0   

                   36        37        38        39        40        41   \
Predict       180166.2  190738.4  174312.4  176903.5  197419.8  180577.4   
Actual value  200000.0  475000.0  173000.0  286000.0  315000.0  192000.0   

                   42        43        44        45        46        47   \
Predict       177281.1  186051.0  183116.0  182763.5  184686.7  178335.7   
Actual value  148500.0  235000.0  104000.0  171500.0  149000.0  180500.0   

                   48        49        50        51        52        53   \
Predict       171530.3  181740.9  180589.8  190586.5  182608.6  181501.6   
Actual value   98000.0  186000.0  210000.0  311500.0  167240.0   97000.0   

                   54        55        56        57        58        59   \
Predict       173136.4  186630.0  186833.1  196568.7  171852.6  183725.0   
Actual value  148000.0  403000.0  110500.0  120000.0  180000.0   76500.0   

                   60        61        62        63        64        65   \
Predict       179313.8  182440.9  186167.6  175928.1  186349.9  178655.9   
Actual value  230000.0  231500.0   73000.0  120500.0  124500.0  201000.0   

                   66        67        68        69        70        71   \
Predict       179466.0  179933.0  177825.5  178087.5  186426.3  176093.6   
Actual value  228500.0  244600.0  179200.0  267000.0  305900.0  187500.0   

                   72        73        74        75        76        77   \
Predict       186838.4  178566.0  190671.3  181861.4  182476.4  189545.0   
Actual value  354000.0  126175.0  242000.0  324000.0  151500.0  154000.0   

                   78        79        80        81        82        83   \
Predict       182170.7  195343.9  176916.8  179333.7  173078.0  170351.9   
Actual value  437154.0  130000.0  145000.0  118000.0  147000.0  165000.0   

                   84        85        86        87        88        89   \
Predict       180019.4  181611.8  171935.6  182775.7  172726.2  182695.2   
Actual value  132000.0  127000.0  187750.0  213500.0  106500.0  123000.0   

                   90        91        92        93        94        95   \
Predict       186843.4  183768.7  174432.9  172897.3  184736.4  174955.5   
Actual value  164990.0  150000.0  145000.0  115000.0  228000.0  181134.0   

                   96        97        98        99        100       101  \
Predict       171613.9  188733.0  182839.1  178005.8  173504.7  183248.6   
Actual value  149500.0  275000.0   79900.0  181000.0   81000.0  116000.0   

                   102       103       104       105       106       107  \
Predict       180938.2  189612.4  188539.8  175384